from __future__ import annotations
from pydantic import BaseModel, Field
from typing import Optional, Literal, Union, Dict, List, Any
from datetime import datetime, timezone

# ==============================================================================
# Domain Models & Field-Level Provenance
# ==============================================================================

class Provenance(BaseModel):
    source_id: str              # which uploaded document/image/csv row
    source_type: Literal["pdf", "image", "csv", "rag_enrichment", "kg_inference", "human_correction", "synthetic_demo"]
    location: Optional[str] = None   # e.g. "page 4, table 2" or "nameplate region top-left"
    extraction_method: str      # e.g. "claude-vision-extraction", "pypdf-text-extraction", "csv-direct", "synthetic-fallback-demo", "rag-category-kb", "human-edit"
    confidence: float = 1.0     # 0.0-1.0
    raw_snippet: Optional[str] = None  # short excerpt supporting this value
    is_synthetic: bool = False  # True if generated by fallback mock/demo data, False if from real document
    observation_type: Literal["directly_observed", "heuristically_inferred", "enriched", "conflicted", "human_verified"] = "directly_observed"

    # Normalization & Unit Conversion Audit Trail
    raw_value: Optional[Union[str, float, int, bool]] = None
    raw_unit: Optional[str] = None
    normalized_value: Optional[Union[str, float, int, bool]] = None
    normalized_unit: Optional[str] = None
    normalization_rule: Optional[str] = None

class FieldValue(BaseModel):
    value: Optional[Union[str, float, int, bool]] = None
    unit: Optional[str] = None
    confidence: float = 1.0
    provenance: List[Provenance] = Field(default_factory=list)
    status: Literal["extracted", "enriched", "conflicted", "human_verified", "missing", "needs_review"] = "missing"
    conflict_candidates: Optional[List[Dict[str, Any]]] = None  # if sources disagree
    is_synthetic: bool = False
    observation_type: Literal["directly_observed", "heuristically_inferred", "enriched", "conflicted", "human_verified"] = "directly_observed"

class ProductRecord(BaseModel):
    product_id: str
    created_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
    updated_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))

    # Core identity
    product_name: FieldValue = Field(default_factory=FieldValue)
    manufacturer: FieldValue = Field(default_factory=FieldValue)
    model_number: FieldValue = Field(default_factory=FieldValue)
    sku: Optional[FieldValue] = None
    category: FieldValue = Field(default_factory=FieldValue)                # links to KG category node

    # Commerce-ready fields
    description_short: FieldValue = Field(default_factory=FieldValue)
    description_long: FieldValue = Field(default_factory=FieldValue)
    key_features: List[FieldValue] = Field(default_factory=list)

    # Industrial Taxonomy & E-Commerce Standards
    unspsc_code: Optional[FieldValue] = None
    etim_class: Optional[FieldValue] = None
    commerce_readiness_score: float = 0.0
    cri_breakdown: Dict[str, float] = Field(default_factory=dict)
    seo_title: Optional[FieldValue] = None
    interchangeable_parts: List[Dict[str, Any]] = Field(default_factory=list)

    # Technical specs (open-ended, category-dependent)
    specifications: Dict[str, FieldValue] = Field(default_factory=dict)   # e.g. {"voltage": FieldValue, "weight_kg": FieldValue}

    # Compliance / commerce
    certifications: List[FieldValue] = Field(default_factory=list)
    warranty: Optional[FieldValue] = None
    country_of_origin: Optional[FieldValue] = None

    # Relationships (Knowledge Graph edges)
    compatible_with: List[str] = Field(default_factory=list)      # product_ids
    replaces: Optional[str] = None
    accessories: List[str] = Field(default_factory=list)

    # Meta
    overall_confidence: float = 0.0
    review_status: Literal["pending", "approved", "needs_review", "rejected"] = "pending"
    human_edits_log: List[Dict[str, Any]] = Field(default_factory=list)

class SourceDocument(BaseModel):
    source_id: str
    source_type: Literal["pdf", "image", "csv"]
    file_path: str
    filename: str
    uploaded_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))

# ==============================================================================
# API Request Models
# ==============================================================================

class PipelineRunRequest(BaseModel):
    source_ids: List[str] = Field(..., min_length=1, description="List of uploaded source IDs to process")
    product_id: Optional[str] = Field(None, description="Optional custom product ID")

class HumanEditRequest(BaseModel):
    value: Union[str, float, int, bool] = Field(..., description="Corrected or updated field value")
    unit: Optional[str] = Field(None, description="Optional measurement unit (e.g. V, kW, kg)")
    reviewer: str = Field("human_reviewer", description="Identifier of the reviewer making the change")
    reason: Optional[str] = Field("human_correction", description="Reason for the manual edit")

# ==============================================================================
# Standardized Error & Metadata Response Models
# ==============================================================================

class ErrorResponse(BaseModel):
    error_code: str = Field(..., description="Stable machine-readable error code")
    message: str = Field(..., description="Human-readable safe explanation of the error")
    details: Optional[Dict[str, Any]] = Field(None, description="Additional context or validation details")

class RootResponse(BaseModel):
    status: str = "online"
    service: str
    version: str
    docs_url: str

class HealthDependencyStatus(BaseModel):
    status: Literal["healthy", "degraded", "unhealthy"]
    details: Optional[str] = None

class HealthCheckResponse(BaseModel):
    status: Literal["healthy", "degraded", "unhealthy"]
    version: str
    timestamp: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
    vlm_mode: Literal["live_claude", "fallback_demo"]
    database: HealthDependencyStatus
    knowledge_graph: HealthDependencyStatus
    seed_kb: HealthDependencyStatus

# ==============================================================================
# Endpoint Response Models
# ==============================================================================

class UploadResponse(BaseModel):
    status: str = "success"
    uploaded_sources: List[SourceDocument]

class DemoLoadResponse(BaseModel):
    status: str = "started"
    job_id: str
    sample_sources: List[str]

class PipelineRunResponse(BaseModel):
    status: str = "started"
    job_id: str

class ProductSummary(BaseModel):
    product_id: str
    product_name: str
    category: str
    overall_confidence: float
    review_status: str
    updated_at: str

class ProductListResponse(BaseModel):
    products: List[ProductSummary]

class ConsistencyWarning(BaseModel):
    field: str
    severity: Literal["info", "warning", "error"] = "warning"
    message: str
    category_avg: Optional[float] = None
    current_value: Optional[float] = None

class ProductDetailResponse(ProductRecord):
    consistency_warnings: List[ConsistencyWarning] = Field(default_factory=list)

class ProductEditResponse(BaseModel):
    status: str = "updated"
    record: ProductRecord

class ProductApproveResponse(BaseModel):
    status: str = "approved"
    record: ProductRecord

class EditHistoryEntry(BaseModel):
    field_name: str
    old_value: Optional[Any] = None
    new_value: Optional[Any] = None
    reviewer: str
    timestamp: str
    reason: Optional[str] = None

class EditHistoryResponse(BaseModel):
    product_id: str
    edit_history: List[EditHistoryEntry]

class KnowledgeGraphNode(BaseModel):
    id: str
    label: str
    type: str
    category: Optional[str] = ""

class KnowledgeGraphLink(BaseModel):
    source: str
    target: str
    relation: str

class KnowledgeGraphResponse(BaseModel):
    nodes: List[KnowledgeGraphNode]
    links: List[KnowledgeGraphLink]

class DiagnosticsResponse(BaseModel):
    timestamp: str
    uptime_seconds: float
    vlm_mode: str
    pipeline_metrics: Dict[str, Any]
    average_stage_latencies_ms: Dict[str, float]
    catalog_and_graph_status: Dict[str, Any]
